//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocoSwap.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocoSwap.Language.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to rules.
        /// </summary>
        public static string add_to_rules {
            get {
                return ResourceManager.GetString("add_to_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List All Vehicles.
        /// </summary>
        public static string all_vehicles {
            get {
                return ResourceManager.GetString("all_vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and add as rule.
        /// </summary>
        public static string and_add_as_rule {
            get {
                return ResourceManager.GetString("and_add_as_rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string apply {
            get {
                return ResourceManager.GetString("apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply all rules.
        /// </summary>
        public static string apply_all_rules {
            get {
                return ResourceManager.GetString("apply_all_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse ....
        /// </summary>
        public static string browse {
            get {
                return ResourceManager.GetString("browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change number.
        /// </summary>
        public static string change_number {
            get {
                return ResourceManager.GetString("change_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string clear_vehicles {
            get {
                return ResourceManager.GetString("clear_vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion.
        /// </summary>
        public static string completion {
            get {
                return ResourceManager.GetString("completion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string completion_completedfailed {
            get {
                return ResourceManager.GetString("completion_completedfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string completion_completedsuccessfully {
            get {
                return ResourceManager.GetString("completion_completedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string completion_notcompleted {
            get {
                return ResourceManager.GetString("completion_notcompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string completion_notindb {
            get {
                return ResourceManager.GetString("completion_notindb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string completion_unknown {
            get {
                return ResourceManager.GetString("completion_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consists in scenario.
        /// </summary>
        public static string consists_in_scenario {
            get {
                return ResourceManager.GetString("consists_in_scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete scenarios.
        /// </summary>
        public static string delete_scenarios {
            get {
                return ResourceManager.GetString("delete_scenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string duration {
            get {
                return ResourceManager.GetString("duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit scenario.
        /// </summary>
        public static string edit_scenario {
            get {
                return ResourceManager.GetString("edit_scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit scenario: {0}.
        /// </summary>
        public static string edit_scenario_title {
            get {
                return ResourceManager.GetString("edit_scenario_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or enter vehicle number manually:.
        /// </summary>
        public static string enter_number_manually {
            get {
                return ResourceManager.GetString("enter_number_manually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string filter {
            get {
                return ResourceManager.GetString("filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip vehicle.
        /// </summary>
        public static string flip {
            get {
                return ResourceManager.GetString("flip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flipped?.
        /// </summary>
        public static string flipped {
            get {
                return ResourceManager.GetString("flipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save date.
        /// </summary>
        public static string game_save_date {
            get {
                return ResourceManager.GetString("game_save_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide played scenarios.
        /// </summary>
        public static string hide_played_scenarios {
            get {
                return ResourceManager.GetString("hide_played_scenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert v.
        /// </summary>
        public static string insert_after {
            get {
                return ResourceManager.GetString("insert_after", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert ^.
        /// </summary>
        public static string insert_before {
            get {
                return ResourceManager.GetString("insert_before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This vehicle in involved in couple/uncouple instructions. LocoSwap will preserve its number..
        /// </summary>
        public static string involved_in_consist_operation {
            get {
                return ResourceManager.GetString("involved_in_consist_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look up vehicles.
        /// </summary>
        public static string look_up_vehicles {
            get {
                return ResourceManager.GetString("look_up_vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load vehicle &quot;{0}&quot;!.
        /// </summary>
        public static string msg_cannot_load_vehicle {
            get {
                return ResourceManager.GetString("msg_cannot_load_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The consist must contain at least one vehicle after the removal!.
        /// </summary>
        public static string msg_consist_empty {
            get {
                return ResourceManager.GetString("msg_consist_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string msg_error {
            get {
                return ResourceManager.GetString("msg_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First time run: Please select Train Simulator directory..
        /// </summary>
        public static string msg_first_time {
            get {
                return ResourceManager.GetString("msg_first_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected vehicle(s) are successfully flipped..
        /// </summary>
        public static string msg_flip_completed {
            get {
                return ResourceManager.GetString("msg_flip_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string msg_message {
            get {
                return ResourceManager.GetString("msg_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a directory first..
        /// </summary>
        public static string msg_no_directory_selected {
            get {
                return ResourceManager.GetString("msg_no_directory_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select vehicles first..
        /// </summary>
        public static string msg_no_vehicle_selected {
            get {
                return ResourceManager.GetString("msg_no_vehicle_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario files successfully saved..
        /// </summary>
        public static string msg_scenario_saved {
            get {
                return ResourceManager.GetString("msg_scenario_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap successfully completed..
        /// </summary>
        public static string msg_swap_completed {
            get {
                return ResourceManager.GetString("msg_swap_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected path is invalid! (Check if it contains RailWorks.exe).
        /// </summary>
        public static string msg_ts_path_invalid {
            get {
                return ResourceManager.GetString("msg_ts_path_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid TS path is required to run this application. The application will now exit..
        /// </summary>
        public static string msg_ts_path_required {
            get {
                return ResourceManager.GetString("msg_ts_path_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle &quot;{0}&quot; is already in replacement rules! Update this rule?.
        /// </summary>
        public static string msg_vehicle_already_in_rules {
            get {
                return ResourceManager.GetString("msg_vehicle_already_in_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles successfully added to replacement rules..
        /// </summary>
        public static string msg_vehicles_added_to_rules {
            get {
                return ResourceManager.GetString("msg_vehicles_added_to_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied while trying to write to scenario files. Please check that Scenario.bin and ScenarioProperties.xml are not write protected..
        /// </summary>
        public static string msg_write_access_denied {
            get {
                return ResourceManager.GetString("msg_write_access_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New vehicle selected.
        /// </summary>
        public static string new_vehicle_selected {
            get {
                return ResourceManager.GetString("new_vehicle_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbering list.
        /// </summary>
        public static string numbering_list {
            get {
                return ResourceManager.GetString("numbering_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbering list not found; please enter number manually..
        /// </summary>
        public static string numbering_list_not_found {
            get {
                return ResourceManager.GetString("numbering_list_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on all stock.
        /// </summary>
        public static string on_all_stock {
            get {
                return ResourceManager.GetString("on_all_stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to only on missing stock (yellows).
        /// </summary>
        public static string only_on_missing_stock {
            get {
                return ResourceManager.GetString("only_on_missing_stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open scenario directory.
        /// </summary>
        public static string open_scenario_directory {
            get {
                return ResourceManager.GetString("open_scenario_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string path {
            get {
                return ResourceManager.GetString("path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player train.
        /// </summary>
        public static string player_train_name {
            get {
                return ResourceManager.GetString("player_train_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading scenario files....
        /// </summary>
        public static string reading_scenario_files {
            get {
                return ResourceManager.GetString("reading_scenario_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string replace {
            get {
                return ResourceManager.GetString("replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace identical.
        /// </summary>
        public static string replace_identical {
            get {
                return ResourceManager.GetString("replace_identical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with.
        /// </summary>
        public static string replace_with {
            get {
                return ResourceManager.GetString("replace_with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement rules.
        /// </summary>
        public static string replacement_rules {
            get {
                return ResourceManager.GetString("replacement_rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement rules management.
        /// </summary>
        public static string replacement_rules_management {
            get {
                return ResourceManager.GetString("replacement_rules_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route.
        /// </summary>
        public static string route {
            get {
                return ResourceManager.GetString("route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule.
        /// </summary>
        public static string rule {
            get {
                return ResourceManager.GetString("rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for....
        /// </summary>
        public static string rule_find {
            get {
                return ResourceManager.GetString("rule_find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with....
        /// </summary>
        public static string rule_replace {
            get {
                return ResourceManager.GetString("rule_replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving scenario files....
        /// </summary>
        public static string saving_scenario {
            get {
                return ResourceManager.GetString("saving_scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning in .ap files....
        /// </summary>
        public static string scanning_ap_files {
            get {
                return ResourceManager.GetString("scanning_ap_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning for vehicle .bin files....
        /// </summary>
        public static string scanning_bin_files {
            get {
                return ResourceManager.GetString("scanning_bin_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario.
        /// </summary>
        public static string scenario {
            get {
                return ResourceManager.GetString("scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected scenario(s) ?.
        /// </summary>
        public static string scenario_delete_prompt_message {
            get {
                return ResourceManager.GetString("scenario_delete_prompt_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenarios deletion.
        /// </summary>
        public static string scenario_delete_prompt_title {
            get {
                return ResourceManager.GetString("scenario_delete_prompt_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** This scenario is contained in an .ap file. LocoSwap will automatically extract it on save. ***.
        /// </summary>
        public static string scenario_in_ap {
            get {
                return ResourceManager.GetString("scenario_in_ap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario name suffix.
        /// </summary>
        public static string scenario_name_suffix {
            get {
                return ResourceManager.GetString("scenario_name_suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        public static string season {
            get {
                return ResourceManager.GetString("season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autumn.
        /// </summary>
        public static string season_autumn {
            get {
                return ResourceManager.GetString("season_autumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spring.
        /// </summary>
        public static string season_spring {
            get {
                return ResourceManager.GetString("season_spring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summer.
        /// </summary>
        public static string season_summer {
            get {
                return ResourceManager.GetString("season_summer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winter.
        /// </summary>
        public static string season_winter {
            get {
                return ResourceManager.GetString("season_winter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Train Simulator Path.
        /// </summary>
        public static string select_ts_path {
            get {
                return ResourceManager.GetString("select_ts_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string start_time {
            get {
                return ResourceManager.GetString("start_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Simulator directory.
        /// </summary>
        public static string ts_directory {
            get {
                return ResourceManager.GetString("ts_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use system language.
        /// </summary>
        public static string use_system_language {
            get {
                return ResourceManager.GetString("use_system_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected vehicle.
        /// </summary>
        public static string vehicle_selected {
            get {
                return ResourceManager.GetString("vehicle_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle to be replaced.
        /// </summary>
        public static string vehicle_to_be_replaced {
            get {
                return ResourceManager.GetString("vehicle_to_be_replaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles in selected consist.
        /// </summary>
        public static string vehicles_in_selected_consist {
            get {
                return ResourceManager.GetString("vehicles_in_selected_consist", resourceCulture);
            }
        }
    }
}
